version: "3"

services:

  frontend:
    container_name: frontend_app 
    build:
      context: ./frontend 
      dockerfile: Dockerfile

    ports: 
      - "3000:3000"
    command: npm start 

  api:
    container_name: server_api 
    build: 
      context: ./server 
      dockerfile: Dockerfile

    ports:
      - "9001:9001"
    
    command: npm start 