version: "3"

services:

  frontend:
    container_name: frontend_app 
    build:
      context: ./frontend 
      dockerfile: ./frontend/Dockerfile

    ports: 
      - "3000:3000"


  api:
    container_name: server_api 
    build: 
      context: ./server 
      dockerfile: ./server/Dockerfile

    ports:
      - "9001:9001"